Corrected error handling in parallelize

diff --git a/scripts/parallelize b/scripts/parallelize
--- a/scripts/parallelize
+++ b/scripts/parallelize
@@ -184,7 +184,7 @@ get_no_of_cpus () {
 
     if [[ -n $digit && $percent -gt 100 ]]; then
       echo "ERROR: Argument -p is a floating number > 1.0"
-      exit
+      exit 1
     fi
     
     # Only recognize percent values if NUM_JOBS < 1.0
@@ -389,15 +389,15 @@ do_parallelize ()
   for ((i=0; i<NUM_JOBS; i++)); do
     if [ ! "${ARG_LIST[$i]}" == "" ]; then
       j=$(($i+1))
-      #echo "Job ${j}/${NUM_JOBS}: ${ARG_LIST[$i]}"
   
       if [ -z "${TEST}" ]; then
         echo "Job ${j}/${NUM_JOBS}: $COMMAND ${ARG_LIST[$i]}" >> "$log"
         nohup bash -c "
           total_k=\$(echo ${ARG_LIST[$i]} | wc -w)
           k_count=0
+          status=0   # 0 means success; 1 means at least one failure
           echo \"\$k_count/\$total_k\" > \"$PROGRESS_DIR/job${i}.progress\"
-          echo 0 > \"$PROGRESS_DIR/job${i}.status\"
+
           for k in ${ARG_LIST[$i]}; do
             ((k_count++))
               
@@ -405,13 +405,14 @@ do_parallelize ()
             echo \"Processing \$k (\$k_count/\$total_k)\" >> \"$log\"
   
             $COMMAND \$k >> \"$log\" 2>&1
-            exit_code=$?
+            exit_code=\$?
             if [ \$exit_code -ne 0 ]; then
-              echo 1 > \"$PROGRESS_DIR/job${i}.status\"
+              status=1
             fi
 
             # Update progress file (instead of printing progress)
             echo \"\$k_count/\$total_k\" > \"$PROGRESS_DIR/job${i}.progress\"
+            echo \$status > \"$PROGRESS_DIR/job${i}.status\"
           done
         " >> "$log" 2>&1 & pids+=($!)
       fi
@@ -425,16 +426,24 @@ do_parallelize ()
         wait "$pid"
       done
 
+      errors=0
+      for ((i=0; i<$NUM_JOBS; i++)); do
+        status=$(cat "$PROGRESS_DIR/job${i}.status")
+        if [[ "$status" -ne 0 ]]; then
+          errors=$(($status+1))
+        fi
+      done
+
       # get overall processing time
       end=$(date +%s)
       runtime=$((end - start))
       hours=$(($runtime / 3600))
       min=$((($runtime / 60) % 60))
       s=$(($runtime % 60))
-      overall="Finished after: "
+      overall="Finished after "
       if [ $hours -gt 0 ]; then overall+="${hours}hrs "; fi
       if [ $min -gt 0 ]; then overall+="${min}min "; fi
-      overall+="${s}sec"
+      overall+="${s}s"
       
       # wait until progress bar is finished
       wait $progress_pid
@@ -442,9 +451,16 @@ do_parallelize ()
         rm -r "$PROGRESS_DIR"  
       fi
 
-      # Display the result
-      echo "${GREEN}-------------------------------------------------------${NC}"
-      echo "${GREEN}${overall}${NC}"
+      # Display the result depending on error status
+      if [[ "$errors" -ne 0 ]]; then
+        overall+=" with errors"
+        echo "${RED}-------------------------------------------------------"
+        echo "${RED}${overall}.${NC}"
+        exit 1
+      else
+        echo "${GREEN}-------------------------------------------------------"
+        echo "${GREEN}${overall}.${NC}"
+      fi
   fi
 }
 
