Changed variable names for folders

diff --git a/scripts/T1Prep b/scripts/T1Prep
--- a/scripts/T1Prep
+++ b/scripts/T1Prep
@@ -490,8 +490,8 @@ surface_estimation()
 {  
   local bname=$1
   local side=$2
-  local outmridir=$3
-  local outsurfdir=$4
+  local mri_dir=$3
+  local surf_dir=$4
   local estimate_spherereg=$5
   local multi=$6
   local nii_ext=$7
@@ -539,7 +539,7 @@ surface_estimation()
 
   # This section of the script checks if a specific hemisphere file exists within a given directory.
   count=0
-  if [ -f "${outmridir}/${Hemi_volume}" ]; then
+  if [ -f "${mri_dir}/${Hemi_volume}" ]; then
 
     # Progress indication
     ((count++))
@@ -550,7 +550,7 @@ surface_estimation()
     # - '-n-avgs 4' sets the number of averages for distance estimation.
     # - '-min-thickness' sets a minimum thickness threshold.
     # - '-fwhm' sets the FWHM for thickness smoothing.
-    ${bin_dir}/CAT_VolThicknessPbt ${verbose} -correct-voxelsize 0.5 -median-filter ${median_filter} -sharpen ${sharpening} -downsample ${downsample} -n-avgs 8 -fwhm ${thickness_fwhm} ${outmridir}/${Hemi_volume} ${outmridir}/${GMT_volume} ${outmridir}/${PPM_volume}
+    ${bin_dir}/CAT_VolThicknessPbt ${verbose} -correct-voxelsize 0.5 -median-filter ${median_filter} -sharpen ${sharpening} -downsample ${downsample} -n-avgs 8 -fwhm ${thickness_fwhm} ${mri_dir}/${Hemi_volume} ${mri_dir}/${GMT_volume} ${mri_dir}/${PPM_volume}
 
     # Updates progress to 'Extract $side surface'.
     ((count++))
@@ -562,7 +562,7 @@ surface_estimation()
     # - '-thresh' sets the isovalue for mesh generation.
     # - '-no-distopen' disables distance-based opening, a form of morphological operation.
     # - '-local-smoothing' applies additional local smoothing to the mesh.
-    ${bin_dir}/CAT_VolMarchingCubes ${verbose} -median-filter ${median_filter} -pre-fwhm ${pre_fwhm} -post-fwhm ${post_fwhm} -thresh ${thresh} ${outmridir}/${PPM_volume} ${outsurfdir}/${Mid_surface}
+    ${bin_dir}/CAT_VolMarchingCubes ${verbose} -median-filter ${median_filter} -pre-fwhm ${pre_fwhm} -post-fwhm ${post_fwhm} -thresh ${thresh} ${mri_dir}/${PPM_volume} ${surf_dir}/${Mid_surface}
 
     # Updates progress to 'Map $side thickness values'.
     ((count++))
@@ -570,19 +570,19 @@ surface_estimation()
 
     # Executes 'CAT_Vol2Surf' to map volumetric data to a surface representation.
     # It uses a weighted average approach for mapping, ranging from -0.4..0.4 of the relative thickness using 5 steps
-    ${bin_dir}/CAT_Vol2Surf -weighted-avg -start -0.4 -steps 5 -end 0.4 ${outsurfdir}/${Mid_surface} ${outmridir}/${GMT_volume} ${outsurfdir}/${PBT_shape}
+    ${bin_dir}/CAT_Vol2Surf -weighted-avg -start -0.4 -steps 5 -end 0.4 ${surf_dir}/${Mid_surface} ${mri_dir}/${GMT_volume} ${surf_dir}/${PBT_shape}
     
     # For thickness_method==3 we use the pure PBT-measure
     if [ "${thickness_method}" -eq 3 ]; then
-      cp ${outsurfdir}/${PBT_shape} ${outsurfdir}/${GMT_shape}
+      cp ${surf_dir}/${PBT_shape} ${surf_dir}/${GMT_shape}
     else
-      ${bin_dir}/CAT_SurfDistance ${verbose} -check_intersect -max 6.0 -mean -thickness ${outsurfdir}/${PBT_shape} ${outsurfdir}/${Mid_surface} ${outsurfdir}/${GMT_shape}
+      ${bin_dir}/CAT_SurfDistance ${verbose} -check_intersect -max 6.0 -mean -thickness ${surf_dir}/${PBT_shape} ${surf_dir}/${Mid_surface} ${surf_dir}/${GMT_shape}
     fi
 
     # Estimate the necessary shift if the threshold is not 0.5
     shift=$(echo "$thresh - $isoval" | bc)
     if (( $(echo "$shift != 0" | bc) )); then
-      ${bin_dir}/CAT_SurfCentral2Pial ${verbose} ${outsurfdir}/${Mid_surface} ${outsurfdir}/${PBT_shape} ${outsurfdir}/${Mid_surface} ${shift}
+      ${bin_dir}/CAT_SurfCentral2Pial ${verbose} ${surf_dir}/${Mid_surface} ${surf_dir}/${PBT_shape} ${surf_dir}/${Mid_surface} ${shift}
     fi    
      
     # Updates progress to 'Deform $side surface'
@@ -590,7 +590,7 @@ surface_estimation()
     if [[ "$multi" -ne -2 ]]; then progress_bar $count $end_count "Refine $side central surface       "; fi
 
     # Obtain more accurate central surface by surface deformation to PPM image
-    ${bin_dir}/CAT_SurfDeform -remove_intersect -isovalue 0.5 -w1 0.1 -w2 0.1 -w3 1.0 -sigma 0.2 ${outmridir}/${PPM_volume} ${outsurfdir}/${Mid_surface} ${outsurfdir}/${Mid_surface}    
+    ${bin_dir}/CAT_SurfDeform -remove_intersect -isovalue 0.5 -w1 0.1 -w2 0.1 -w3 1.0 -sigma 0.2 ${mri_dir}/${PPM_volume} ${surf_dir}/${Mid_surface} ${surf_dir}/${Mid_surface}    
 
     # Executes 'CAT_Surf2PialWhite' to estimate both pial and white matter surfaces.
     # - '-w1' sets the internal smoothness weight.
@@ -604,10 +604,10 @@ surface_estimation()
       # Updates progress to 'Deform $side surface'
       ((count++))
       if [[ "$multi" -ne -2 ]]; then progress_bar $count $end_count "Estimate $side pial and white surface     "; fi
-      ${bin_dir}/CAT_Surf2PialWhite ${verbose} -w1 0.1 -w2 0.2 -w3 0.4 -w4 0 -sigma 0.3 -iter 50 ${outsurfdir}/${Mid_surface} ${outsurfdir}/${GMT_shape} ${outmridir}/${Hemi_volume} ${outsurfdir}/${Pial_surface} ${outsurfdir}/${WM_surface}
+      ${bin_dir}/CAT_Surf2PialWhite ${verbose} -w1 0.1 -w2 0.2 -w3 0.4 -w4 0 -sigma 0.3 -iter 50 ${surf_dir}/${Mid_surface} ${surf_dir}/${GMT_shape} ${mri_dir}/${Hemi_volume} ${surf_dir}/${Pial_surface} ${surf_dir}/${WM_surface}
 
       # Get central surface by averaging pial and white matter surface
-      ${bin_dir}/CAT_AverageSurfaces -avg ${outsurfdir}/${Mid_surface} ${outsurfdir}/${Pial_surface} ${outsurfdir}/${WM_surface}    
+      ${bin_dir}/CAT_AverageSurfaces -avg ${surf_dir}/${Mid_surface} ${surf_dir}/${Pial_surface} ${surf_dir}/${WM_surface}    
     fi
           
     # Optionally estimate thickness by using the mean distance (Tfs) between pial and white matter surface and limit to maximum of 6.0
@@ -615,20 +615,20 @@ surface_estimation()
       # Updates progress to 'Refine $side thickness'
       ((count++))
       if [[ "$multi" -ne -2 ]]; then progress_bar $count $end_count "Refine $side thickness            "; fi
-      ${bin_dir}/CAT_SurfDistance -max 6.0 -mean ${outsurfdir}/${Pial_surface} ${outsurfdir}/${WM_surface} ${outsurfdir}/${GMT_shape}
+      ${bin_dir}/CAT_SurfDistance -max 6.0 -mean ${surf_dir}/${Pial_surface} ${surf_dir}/${WM_surface} ${surf_dir}/${GMT_shape}
     fi
     
     # Correct cortical thickness that is influenced by folding
     if [ "${correct_folding}" -eq 1 ]; then
-      ${bin_dir}/CAT_SurfCorrectThicknessFolding -max 6.0 ${outsurfdir}/${Mid_surface} ${outsurfdir}/${GMT_shape} ${outsurfdir}/${GMT_shape}
+      ${bin_dir}/CAT_SurfCorrectThicknessFolding -max 6.0 ${surf_dir}/${Mid_surface} ${surf_dir}/${GMT_shape} ${surf_dir}/${GMT_shape}
     fi
 
     # Map intensity values of bias-corrected image from central, pial, and white surface for debugging
-    if [[ "${debug}" -eq 1 && -f "${outmridir}/${mT1_volume}" ]]; then
-      ${bin_dir}/CAT_Vol2Surf -start 0 -steps 1 -end 0 ${outsurfdir}/${Mid_surface} ${outmridir}/${mT1_volume} ${outsurfdir}/${Intensity_Mid}
+    if [[ "${debug}" -eq 1 && -f "${mri_dir}/${mT1_volume}" ]]; then
+      ${bin_dir}/CAT_Vol2Surf -start 0 -steps 1 -end 0 ${surf_dir}/${Mid_surface} ${mri_dir}/${mT1_volume} ${surf_dir}/${Intensity_Mid}
       if [ "${save_pial_white}" -eq 1 ]; then
-        ${bin_dir}/CAT_Vol2Surf -start 0 -steps 1 -end 0 ${outsurfdir}/${Pial_surface} ${outmridir}/${mT1_volume} ${outsurfdir}/${Intensity_Pial}
-        ${bin_dir}/CAT_Vol2Surf -start 0 -steps 1 -end 0 ${outsurfdir}/${WM_surface} ${outmridir}/${mT1_volume} ${outsurfdir}/${Intensity_WM}
+        ${bin_dir}/CAT_Vol2Surf -start 0 -steps 1 -end 0 ${surf_dir}/${Pial_surface} ${mri_dir}/${mT1_volume} ${surf_dir}/${Intensity_Pial}
+        ${bin_dir}/CAT_Vol2Surf -start 0 -steps 1 -end 0 ${surf_dir}/${WM_surface} ${mri_dir}/${mT1_volume} ${surf_dir}/${Intensity_WM}
       fi
     fi
   
@@ -638,25 +638,25 @@ surface_estimation()
       ((count++))
       if [[ "$multi" -ne -2 ]]; then progress_bar $count $end_count "Spherical inflation $side hemisphere  "; fi
       # Inflates the surface to a sphere with additional areal smoothing.
-      ${bin_dir}/CAT_Surf2Sphere ${outsurfdir}/${Mid_surface} ${outsurfdir}/${Sphere_surface} 6
+      ${bin_dir}/CAT_Surf2Sphere ${surf_dir}/${Mid_surface} ${surf_dir}/${Sphere_surface} 6
   
       # Updates progress to 'Spherical estimate_spherereg $side hemisphere'.
       ((count++))
       if [[ "$multi" -ne -2 ]]; then progress_bar $count $end_count "Spherical estimate_spherereg $side hemisphere"; fi
       # Warps the surface to align with a standard sphere template, using specific mapping steps and averaging options.
-      ${bin_dir}/CAT_SurfWarp ${verbose} -steps 2 -avg -i ${outsurfdir}/${Mid_surface} -is ${outsurfdir}/${Sphere_surface} -t ${Fsavg} -ts ${Fsavgsphere} -ws ${outsurfdir}/${Spherereg_surface}
+      ${bin_dir}/CAT_SurfWarp ${verbose} -steps 2 -avg -i ${surf_dir}/${Mid_surface} -is ${surf_dir}/${Sphere_surface} -t ${Fsavg} -ts ${Fsavgsphere} -ws ${surf_dir}/${Spherereg_surface}
     fi
 
     # remove temporary files if not debugging
     if [ "${debug}" -eq 0 ]; then
-      rm ${outmridir}/${GMT_volume} ${outmridir}/${PPM_volume}
+      rm ${mri_dir}/${GMT_volume} ${mri_dir}/${PPM_volume}
     fi
 
     return 0
 
   else
     if [ "${estimate_seg}" -eq 0 ]; then
-      echo "${RED}ERROR: Could not find ${outmridir}/${Hemi_volume}. Please run T1Prep with the '--hemisphere' flag first.${NC}" >&2
+      echo "${RED}ERROR: Could not find ${mri_dir}/${Hemi_volume}. Please run T1Prep with the '--hemisphere' flag first.${NC}" >&2
     else
       echo "${RED}ERROR: ${python} ${src_dir}/segment.py failed.${NC}" >&2
     fi
@@ -886,21 +886,22 @@ process()
     
     # get output folders for surfaces and volumes
     if [[ "${use_bids_naming}" -eq 1 || "${use_subfolder}" -eq 0 ]]; then  
-      outmridir=${outdir0}
-      outsurfdir=${outdir0}
+      mri_dir=${outdir0}
+      surf_dir=${outdir0}
+      report_dir=${outdir0}
+      label_dir=${outdir0}
     else
-      outmridir=${outdir0}/mri
-      outsurfdir=${outdir0}/surf
+      mri_dir=${outdir0}/mri
+      surf_dir=${outdir0}/surf
+      report_dir=${outdir0}/report
+      label_dir=${outdir0}/label
     fi
               
-    # create output folders if needed
-    if [ ! -d "$outmridir" ]; then
-      mkdir -p "$outmridir"
-    fi
-    if [ ! -d "$outsurfdir" ]; then
-      mkdir -p "$outsurfdir"
-    fi
-
+    # create output folders    
+    dir_list="$mri_dir"
+    [ "${save_surf}" -eq 1 ] && dir_list+=" $surf_dir"
+    mkdir -p $dir_list
+        
     # print progress and filename
     j=$(expr $i + 1)
     if [ "${multi}" -ne -2 ]; then
@@ -938,7 +939,7 @@ process()
       [ "${save_csf}" -eq 1 ] && cmd+=" --csf"   
       
       cmd+=" --vessel \"${vessel}\""
-      cmd+=" --input \"${input}\" --outdir \"${outmridir}\""
+      cmd+=" --input \"${input}\" --outdir \"${mri_dir}\""
       
       # Execute the command and capture exit code
       if [ "${estimate_seg}" -eq 1 ]; then
@@ -975,7 +976,7 @@ process()
       # check for outputs from previous step
       pids=()
       for side in left right; do
-        surface_estimation $bname $side $outmridir $outsurfdir $estimate_spherereg $multi $nii_ext &
+        surface_estimation $bname $side $mri_dir $surf_dir $estimate_spherereg $multi $nii_ext &
         pids+=("$!")
       done
 
